### PR TITLE
feat: create index html

### PR DESCRIPTION
**Pull request by jpgsaraceni**
This PR adds index.html to root directory of repository. This file will be used to test conflicts and show the use of `git rebase`.

### CODE REVIEW

**Review by filipeleaogomes — APPROVED** [review]

**Review by ceciliaromao — APPROVED** [review]

**Review by Guyrlam — APPROVED** [review]

**Review by Fabio-Cesar — APPROVED** [review]
Approved.

**Review by antoniofco22 — APPROVED** [review]
aprovado

**Review by janascher — APPROVED** [review]
Ok!

**Review by nayandrade — APPROVED** [review]
👍 joinha

**Review by rogeriokotsubo — APPROVED** [review]

**Review by marcusfreirepaulino — APPROVED** [review]

**Review by leonardoandradevieira — APPROVED** [review]

**Review by geversonfernandes — APPROVED** [review]

**Review by YanVictorSN — APPROVED** [review]

**Pull request merged**
